apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secret
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.jwtSecret | quote }}
