apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "home-app.fullname" . }}-frontend
  labels:
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: {{ include "home-app.frontend.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: BACKEND_HOST
              value: {{ include "home-app.fullname" . }}-backend
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
