apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "home-app.fullname" . }}
spec:
  hostnames:
    - {{ .Values.httproute.hostname }}
  parentRefs:
    - name: {{ required "httproute.parentRef.name is required" .Values.httproute.parentRef.name }}
      namespace: {{ .Values.httproute.parentRef.namespace | default "default" }}
  rules:
    - {{- if .Values.httproute.backendTimeout }}
      timeouts:
        request: {{ .Values.httproute.backendTimeout }}
      {{- end }}
      matches:
        - path:
            type: PathPrefix
            value: /api/
      backendRefs:
        - group: ""
          kind: Service
          name: {{ include "home-app.fullname" . }}-backend
          port: {{ .Values.backend.port }}
          weight: 1
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: {{ include "home-app.fullname" . }}-frontend
          port: {{ .Values.frontend.port }}
          weight: 1