apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-app.fullname" . }}-backend
  labels:
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/component: backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
