apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-app.fullname" . }}-frontend
  labels:
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/component: frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
